Helper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.SystemList.as_view(), name='main'),
    url(r'(?P<sys_slug>[-\w]+)/$', views.SystemDetail.as_view(), name='system-detail'),
    url(r'(?P<sys_slug>[-\w]+)/(?P<elem_slug>[-\w]+)/$', views.ElementDetail.as_view(), name='element-detail'),
]

#id(?P<elem_id>[0-9]+)
"""url(r'(?P<sys_slug>[-\w]+)/(?P<elem_slug>[-\w]+)/$',
views.ElementDetail.as_view(), name = 'element-detail' """

NPPHelper/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^helper/', include('Helper.urls'))
]

Helper/models.py
from django.db import models
from django.template.defaultfilters import slugify

TYPE_CHOICES = (
    ('ЗАДВ', 'Задвижка'),
    ('ОК', 'Обратный клапан'),
    ('РЕГ', 'Регулятор'),
    ('Н', 'Насос'),
    ('ТА', 'Турбоагрегат'),
    ('Т/О', 'Теплообменник'),
    ('К', 'Конденсатор'),
    ('КС', 'Конденсатосборник'),
    ('Б', 'Бак'),
    ('ДРЕН', 'Дренаж'),
)


class System(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    short_name = models.CharField(max_length=8, verbose_name='Короткое обозначение')
    info = models.CharField(max_length=250, null=True, blank=True, verbose_name='Описание системы')
    img = models.ImageField(verbose_name='Принципиальная схема', null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.short_name).upper()
        super(System, self).save(*args, **kwargs)

    def __str__(self):
        return '{} - {}'.format(self.short_name, self.name)

    class Meta:
        verbose_name_plural = 'Системы'

class Element(models.Model):
    name = models.CharField(max_length=16, verbose_name='Маркировка')
    info = models.CharField(max_length=200, verbose_name='Название и назначение', blank=True)
    defect = models.CharField(max_length=250, default='Нет дефектов', verbose_name='Дефекты')
    system = models.ForeignKey('System', on_delete=models.CASCADE, null=True, verbose_name='Система элемента')
    type = models.CharField(max_length=4, choices=TYPE_CHOICES, default='ЗАДВ', verbose_name='Тип')
    row = models.CharField(max_length=4, default='А-В', verbose_name='Ряд(ы)')
    axis = models.CharField(max_length=10, default='1-12', verbose_name='Ось(оси)')
    img = models.ImageField(null=True, blank=True,verbose_name='Чертеж,фото,схема')
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name).upper()
        super(Element, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Элементы системы'

Helper/views.py
from django.views.generic import ListView, DetailView
from .models import System, Element


class SystemList(ListView):
    template_name = 'helper/main.html'
    model = System
    context_object_name = 'systems'


class SystemDetail(DetailView):
    template_name = 'helper/system_detail.html'
    context_object_name = 'system'
    model = System
    slug_url_kwarg = 'sys_slug'


class ElementDetail(DetailView):
    template_name = 'helper/element_detail.html'
    context_object_name = 'element'
    model = Element
    slug_url_kwarg = 'elem_slug'

Helper/templates/helper/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link href='http://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Kaushan+Script|Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Istok+Web|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href={% static "helper/libs/bootstrap/css/bootstrap.min.css" %}>
  <link rel="stylesheet" href={% static "helper/libs/fa/css/font-awesome.min.css" %}>
  <link rel="stylesheet" href={% static "helper/main.css" %}>
  <script src={% static "helper/libs/jquery-3.1.1.min.js" %}></script>
  <script src={% static "helper/libs/bootstrap/js/bootstrap.min.js" %}></script>
  <script src={% static "helper/js/common.js" %}></script>
  <title>{% block title %}{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
   {% block content %}{% endblock %}
</body>
</html>

Helper/templates/helper/element_detail.html
{% extends 'helper/base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <h1>{{ element }}</h1>
        <h2>Информация об элементе:</h2>
        <p>{{ element.info }}</p>
        <h2>Расположение {{ element }}</h2>
        <p>Ряд(ы): {{ element.row }}</p>
        <p>Ось(оси): {{ element.axis }}</p>
        {% if element.defects %}
          <h2>Дефекты</h2>
          <p>{{ element.defects | date }}</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

Helper/templates/helper/elements.html
{% extends 'helper/base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <h1>Элементы системы:</h1>
        {% for element in elements %}
          <p>{{ element }} - {{ element.info }} </p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

Helper/templates/helper/main.html
{% extends 'helper/base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <h1>Welcome to NPPHelper ver.1.0</h1>
        {% for system in systems %}
          <a href="{% url 'system-detail' system.slug %}">
            <p>{{ system }}</p>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

Helper/templates/helper/system_detail.html
{% extends 'helper/base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <h1>{{ system }}</h1>
        <h2>Описание системы:</h2>
        <p>{{ system.info }}</p>
        <h2>Элементы системы:</h2>
{% for element in system.element_set.all %}
  <a href="{% url 'element-detail' system.slug element.slug %}">
    <p>{{ element }}</p>
  </a>
 {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}